#!/usr/bin/env python3
"""Render a benchmark run's JSONL records into a markdown report.

    tools/bench/report.py E2E.jsonl MICRO.jsonl > report.md

Generated, never hand-edited: rerunning over the same inputs produces the same file. The report
carries raw distributions only. Every record is checked for the `baseline-unclassified` verdict
and the report refuses to render one that claims anything else, because no verdict is justified
before 0.4.0's A/A noise floor exists.
"""

import json
import sys

WORKLOADS = [
    "floor.health",
    "read.get",
    "create.nested",
    "update.ops",
    "batch.50",
    "query.protected",
    "include.wide",
]


def load(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def fail(message):
    print(f"report.py: {message}", file=sys.stderr)
    sys.exit(1)


def us(value):
    return f"{value:,.1f}"


def main():
    if len(sys.argv) != 3:
        fail("usage: report.py E2E.jsonl MICRO.jsonl")
    e2e, micro = load(sys.argv[1]), load(sys.argv[2])
    for r in e2e + micro:
        if r.get("verdict") != "baseline-unclassified":
            fail(f"record carries verdict {r.get('verdict')!r}; this report publishes none")

    measured = [r for r in e2e if r["kind"] == "e2e"]
    historical = [r for r in e2e if r["kind"] == "historical"]
    if not measured:
        fail(f"{sys.argv[1]} has no e2e records")
    ctx = measured[0]["context"]
    rungs = sorted({r["db_latency_rung_ms"] for r in measured})
    calibration = [r for r in e2e if r["kind"] == "calibration"]
    cell = {(r["target"], r["workload"], r["db_latency_rung_ms"]): r for r in measured + historical}

    out = []
    w = out.append
    w("# Benchmark baseline, 0.3.0")
    w("")
    w("Generated by `tools/bench/report.py` from the JSONL records beside this file. Do not edit by")
    w("hand; rerun `tools/bench/gate-j.sh` instead.")
    w("")
    w("**Every number here is `baseline-unclassified`.** No `faster`, `slower` or `equivalent`")
    w("verdict is published at 0.3.0, because the A/A noise floor that would justify one is 0.4.0")
    w("work. A difference between two columns below is an observation, not a claim.")
    w("")
    w("## Context")
    w("")
    w(f"- run: `{measured[0]['run_id']}`")
    w(f"- parse-rust: `{ctx['parse_rust_sha'][:12]}`" + (" (dirty tree)" if ctx["parse_rust_dirty"] else ""))
    w(f"- parse-server: `{ctx['upstream']['sha'][:12]}`, clean: {str(ctx['upstream']['clean']).lower()}")
    w(f"- node `{ctx['node']}`, `{ctx['rustc']}`")
    w(f"- {ctx['cpu']}, {ctx['os']}")
    p = measured[0]["params"]
    w(f"- concurrency {p['concurrency']}, {p['samples']} samples after {p['warmup']} warmup per cell")
    w("- database latency is injected per command by toxiproxy between each server and MongoDB")
    w("")
    w("## End to end")
    w("")
    w("Latency is wall clock per request in microseconds. Database time is the union of command")
    w("intervals attributed to the request, measured inside each server by command monitoring.")
    w("The 10 ms rung is the calibration point: on workloads whose commands run one after another,")
    w("database time must be the command count times 10 ms within tolerance, or the run fails.")
    for rung in rungs:
        w("")
        w(f"### {rung} ms per database command")
        w("")
        w("| workload | target | p50 | p99 | db p50 | db ops | db share |")
        w("|---|---|---:|---:|---:|---:|---:|")
        for workload in WORKLOADS:
            for target in ["node", "rust"]:
                r = cell.get((target, workload, rung))
                if r is None:
                    fail(f"missing cell {target} {workload} {rung} ms")
                lat = r["latency_us"]
                w(
                    f"| `{workload}` | {target} | {us(lat['p50'])} | {us(lat['p99'])} "
                    f"| {us(r['db_micros_p50'])} | {r['db_ops_p50']} | {r['db_share_p50']:.3f} |"
                )
    if calibration:
        w("")
        w("### Calibration at 10 ms")
        w("")
        w("| target | workload | db p50 | db ops | expected | passed |")
        w("|---|---|---:|---:|---:|---|")
        for r in calibration:
            w(
                f"| {r['target']} | `{r['workload']}` | {us(r['db_micros_p50'])} "
                f"| {r['db_ops_p50']:g} | {us(r['expected_micros'])} | {str(r['passed']).lower()} |"
            )
    if historical:
        w("")
        w("## Historical diagnostic")
        w("")
        w("The published 0.2.0 and 0.2.1 binaries, run on the same machine and workloads. Wall clock")
        w("only: they were built without instrumentation, so they report no database time. They are")
        w("outside the completeness matrix and are printed for reference, not compared.")
        versions = sorted({r["target"] for r in historical})
        for rung in rungs:
            w("")
            w(f"### {rung} ms per database command")
            w("")
            w("| workload | " + " | ".join(f"{v} p50" for v in versions) + " | rust p50 |")
            w("|---|" + "---:|" * (len(versions) + 1))
            for workload in WORKLOADS:
                row = []
                for v in versions + ["rust"]:
                    r = cell.get((v, workload, rung))
                    row.append(us(r["latency_us"]["p50"]) if r else "not measured")
                w(f"| `{workload}` | " + " | ".join(row) + " |")

    w("")
    w("## Microbenchmarks")
    w("")
    w("p50 per operation in microseconds, over the frozen corpora. Each record carries the hash of")
    w("the corpus file it ran on.")
    w("")
    families = sorted({r["family"] for r in micro})
    corpora = sorted({r["corpus"]["name"] for r in micro})
    mcell = {(r["target"], r["family"], r["corpus"]["name"]): r for r in micro}
    w("| corpus | " + " | ".join(f"{f} rust | {f} node" for f in families) + " |")
    w("|---|" + "---:|" * (2 * len(families)))
    for corpus in corpora:
        row = []
        for family in families:
            for target in ["rust", "node"]:
                r = mcell.get((target, family, corpus))
                if r is None:
                    fail(f"missing micro cell {target} {family} {corpus}")
                row.append(f"{r['latency_us']['p50']:.3f}")
        w(f"| `{corpus}` | " + " | ".join(row) + " |")
    w("")
    w("## Methods")
    w("")
    for family in families:
        for target in ["rust", "node"]:
            r = next(r for r in micro if r["family"] == family and r["target"] == target)
            w(f"- `{family}`, {target}: {r['method']}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
